//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemestralProject.Resources.Dummy {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Dummy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dummy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SemestralProject.Resources.Dummy.Dummy", typeof(Dummy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jnovak123@volny.cz
        ///kpospisilova87@tiscali.cz
        ///tnovotny456@gmail.com
        ///petr.marek789@googlemail.com
        ///kprochazkova101@yahoo.com
        ///rrichter2022@seznam.cz
        ///svoboda007@email.cz
        ///urbanova99@gmail.com
        ///j.kadlec777@yahoo.com
        ///m.novakova123@volny.cz
        ///p.pokorny456@gmail.com
        ///lucie.richterova987@yahoo.com
        ///kuba.vavra55@tiscali.cz
        ///d.dolezal888@gmail.com
        ///anna.urbanova777@yahoo.com
        ///m.svoboda333@email.cz
        ///p.prochazka2023@gmail.com
        ///k.benesova456@seznam.cz
        ///navratilova123@email.cz
        ///holub456@gmail.com
        ///jnovak2023@volny.cz [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EMAILS {
            get {
                return ResourceManager.GetString("EMAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAAK/INwWK6QAAABl0RVh0U29mdHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAALeSURBVDjLY/j//z8DDKvNusuTturRzro9L95NO/b674RDr37W73z+Pmnxg9PypRcUkNXCMIaAcu9Nj7rjb24ee/rt/9HH3/47zry7Si7/vKZM5hlGggYodd5g1J9wc+KiKx8+Wk+5vSh367OLlp3XF8kknxbGphnDAIWGK4kbb37+pV13pV82+6xF1Y7nt90m3NwinX3JWrP51hzz3nsHTTrv7jZpvbPbrPXWQc3Sa8sQmqsuq5bsfHF15ul3b2TSzphJx5/UmXLw9Wv/KbcPSGdecFauuDnZZ97jz9kbX/zPXPPiv07pjXXisRfK4AYYtVydufn6pz/zTr77MOHAqxczDr5+e+Dmp/+xs+6eEfM6IKffcGt9wLxH/5x6795NXPbkv0T0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IMAGES {
            get {
                return ResourceManager.GetString("IMAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hradec Králové
        ///České Budějovice
        ///Liberec
        ///Olomouc
        ///Pardubice
        ///Zlín
        ///Karlovy Vary
        ///Jihlava
        ///Třebíč
        ///Kutná Hora
        ///Český Krumlov
        ///Litomyšl
        ///Kroměříž
        ///Žďár nad Sázavou
        ///Hodonín
        ///Frýdek-Místek
        ///Kolín
        ///Prostějov
        ///Tábor
        ///Chrudim
        ///Ústí nad Labem
        ///Plzeň
        ///Brno
        ///Ostrava
        ///Jablonec nad Nisou
        ///Kladno
        ///Opava
        ///Havířov
        ///Most
        ///Česká Lípa
        ///Jindřichův Hradec
        ///Teplice
        ///Děčín
        ///Klatovy
        ///Nový Jičín
        ///Kroměříž
        ///Znojmo
        ///Trutnov
        ///Česká Třebová
        ///Uherské Hradiště
        ///Sokolov
        ///Chomutov
        ///Ústí nad Orlicí
        ///Hradec nad Moravicí
        ///Litvínov
        ///Vsetín [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MUNICIPALITIES {
            get {
                return ResourceManager.GetString("MUNICIPALITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nová Ves
        ///Dolní Lhota
        ///Horní Háj
        ///Staré Město
        ///Nové Město
        ///Dolní Újezd
        ///Horní Polanka
        ///Nový Dvůr
        ///Podlesí
        ///Hlavní Čtvrť
        ///Nová Čtvrť
        ///Starý Přívoz
        ///Nový Svět
        ///Horní Kout
        ///Dolní Dubina
        ///Nový Háj
        ///Staré Časy
        ///Nové Sady
        ///Horní Potůčky
        ///Dolní Líšnice
        ///Háje
        ///Louky
        ///Polanka
        ///Újezd
        ///Sady
        ///Přívoz
        ///Ves
        ///Lhota
        ///Potůčky
        ///Dubina.
        /// </summary>
        internal static string MUNIPARTS {
            get {
                return ResourceManager.GetString("MUNIPARTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petr
        ///Kateřina
        ///Jan
        ///Barbora
        ///Tomáš
        ///Veronika
        ///Martin
        ///Tereza
        ///Lukáš
        ///Karolína
        ///Jakub
        ///Anna
        ///Michal
        ///Adéla
        ///David
        ///Lucie
        ///Marek
        ///Eliška
        ///Filip
        ///Nikola
        ///Adam
        ///Kristýna
        ///Josef
        ///Jana
        ///Vojtěch
        ///Markéta
        ///Ondřej
        ///Eliška
        ///Radek
        ///Michaela
        ///Filip
        ///Šárka
        ///Martin
        ///Petra
        ///Jakub
        ///Veronika
        ///Matěj
        ///Pavlína
        ///David
        ///Karolína
        ///Marek
        ///Lenka
        ///Pavel
        ///Alena
        ///Tomáš
        ///Simona
        ///Lukáš
        ///Iveta
        ///Jakub
        ///Nikola
        ///Václav
        ///Tereza
        ///Petr
        ///Kristýna
        ///Matěj
        ///Eliška
        ///Martin
        ///Marie
        ///David
        ///Kateřina.
        /// </summary>
        internal static string NAMES {
            get {
                return ResourceManager.GetString("NAMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO ROLE (id, nazev) VALUES (10, &apos;Správce lidských zdrojů&apos;)
        ///INSERT INTO ROLE (id, nazev) VALUES (11, &apos;Správce ICT&apos;)
        ///INSERT INTO ROLE (id, nazev) VALUES (12, &apos;Dispečer&apos;)
        ///INSERT INTO ROLE (id, nazev) VALUES (13, &apos;Manager&apos;)
        ///INSERT INTO ROLE (id, nazev) VALUES (14, &apos;Řidič&apos;)
        ///INSERT INTO PRAVA(role, opravneni) VALUES (10, 3)
        ///INSERT INTO PRAVA(role, opravneni) VALUES (10, 7)
        ///INSERT INTO PRAVA(role, opravneni) VALUES (10, 8)
        ///INSERT INTO PRAVA(role, opravneni) VALUES (10, 20)
        ///INSERT INTO PRAVA(role, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ROLE {
            get {
                return ResourceManager.GetString("ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Havlíčkova
        ///Masarykova
        ///Nová
        ///Palackého
        ///Husova
        ///Svobody
        ///Jiráskova
        ///Náměstí Míru
        ///Rooseveltova
        ///28. října
        ///Wilsonova
        ///Nádražní
        ///Křižíkova
        ///Vinohradská
        ///Vrchlického
        ///Riegrova
        ///Celetná
        ///Pařížská
        ///Panská
        ///Štefánikova
        ///Havelská
        ///Mozartova
        ///Lidická
        ///Ulička
        ///Rybníček
        ///Stromovka
        ///Zahradní
        ///U Tržnice
        ///Smetanova
        ///Poděbradská
        ///Divadelní
        ///Rudolfovská
        ///U Potoka
        ///Březová
        ///U Lesa
        ///Žižkova
        ///Horská
        ///Vltavská
        ///U Zámku
        ///Staroměstská
        ///U Cihelny
        ///Slezská
        ///Na Hradbách
        ///U Kapličky
        ///Palachova
        ///Podzámecká
        ///Hlaváčkova
        ///Kollárova
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string STREETS {
            get {
                return ResourceManager.GetString("STREETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novák
        ///Svobodová
        ///Novotný
        ///Procházková
        ///Dvořák
        ///Pospíšilová
        ///Malý
        ///Vávrová
        ///Marek
        ///Štěpánová
        ///Urban
        ///Růžičková
        ///Kučera
        ///Hájková
        ///Kohout
        ///Němcová
        ///Jirásek
        ///Křížová
        ///Vaněk
        ///Šimečková
        ///Pospíchal
        ///Tichý
        ///Horák
        ///Kadlec
        ///Ševčík
        ///Veselý
        ///Král
        ///Černý
        ///Kovařík
        ///Holub
        ///Mareš
        ///Jelínek
        ///Štěpánek
        ///Urbanec
        ///Blažek
        ///Navrátil
        ///Růžička
        ///Pekárek
        ///Zeman
        ///Beneš
        ///Novotný
        ///Kovář
        ///Marek
        ///Nováková
        ///Pokorný
        ///Richter
        ///Konečný
        ///Vávra
        ///Doležal
        ///Urbanová
        ///Svoboda
        ///Procházka
        ///Benešová
        ///Navrátilová
        ///Holubová
        ///Kadlecová
        ///Tichá
        ///Růžičková        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SURNAMES {
            get {
                return ResourceManager.GetString("SURNAMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 110 00
        ///370 05
        ///500 02
        ///602 00
        ///779 00
        ///360 01
        ///415 01
        ///602 00
        ///746 01
        ///783 71
        ///110 01
        ///500 03
        ///779 01
        ///602 00
        ///370 04
        ///415 02
        ///746 02
        ///783 72
        ///360 05
        ///783 73
        ///602 01
        ///779 02
        ///500 04
        ///110 02
        ///746 03
        ///370 06
        ///602 02
        ///783 74
        ///415 03
        ///360 06
        ///110 03
        ///779 03
        ///602 03
        ///500 05
        ///746 04
        ///415 04
        ///360 07
        ///783 75
        ///370 07
        ///602 04
        ///110 04
        ///779 04
        ///500 06
        ///746 05
        ///415 05
        ///360 08
        ///783 76
        ///370 08
        ///602 05
        ///110 05.
        /// </summary>
        internal static string ZIPCODES {
            get {
                return ResourceManager.GetString("ZIPCODES", resourceCulture);
            }
        }
    }
}
