    /*
     * Gets last generated number of sequence.
     * :param p_seq: Name of sequence.
     * :returns:     Last generated number of sequence,
     *               or -2147483648 if any error occurs.
     */
--
    /*
     * Gets next number from sequence.
     * :param p_seq: Name of sequence.
     * :returns:     Next number from sequence, 
     *               or -2147483648 if any error occurs.
     */
--
